In [1]:
## 퍼셉트론 및 인공지능, 머신러닝, 딥 러닝 개요에 대해 알아보자 
## deeplearning.pdf 참고
## 신경망 구성시 Tensorflow 사용하여 진행할 것 

In [2]:
'''
TensorFlow
 구글이 공개한 대규모 숫자 계산을 해주는 머신러닝 및 딥러닝 전문 라이브러리
 Tensor는 다차원 행렬 계산을 의미
 상업적인 용도로 사용할 수 있는 오픈소스(Apache 2.0)
 C++로 만들어진 라이브러리
 파이썬을 사용해서 호출할 때 오버헤드가 거의 없는 구조로 설계
 https://www.tensorflow.org
 이미지 처리와 음향 처리 등을 할 때는 추가적으로 이미지 처리에 특화된 OpenCV 라이브러리등과 함께
사용
'''
## 주의 : 하단 코드는 필시 1.X 버전의 tensorflow환경에서만 실행할것
## 현재 .ipynb파일은 1.15버전의 gpu가상환경에서 생성 

import tensorflow as tf
print(tf.__version__)

1.15.0


In [3]:
import tensorflow as tf
#상수 정의
a = tf.constant(1234)
b = tf.constant(5000)
#계산 정의
add_op = a+b
#세션 시작
sess = tf.Session()
res = sess.run(add_op) #계산식 평가
print(res)

6234


In [4]:
import tensorflow as tf
#상수 정의
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)
#계산 정의
calc1_op = a + b *c
calc2_op = (a+b) * c
#세션 시작
sess = tf.Session()
res1 = sess.run(calc1_op) #계산식 평가
print(res1)
res2 = sess.run(calc2_op) #계산식 평가
print(res2)

14
20


In [5]:
import tensorflow as tf
#상수 정의
a = tf.constant(100)
b = tf.constant(50)
add_op = a+ b
#변수 v 선언하기
v = tf.Variable(0)
# 변수 v에 add_op의 결과 대입하기
let_op = tf.assign(v, add_op)
#세션 시작
sess = tf.Session()
# 변수 초기화히기 (메모리에 생성)
sess.run(tf.global_variables_initializer())
#계산식 실행
sess.run(let_op)
print(sess.run(v))

150


In [6]:
'''
 placeholder – 템플릿처럼 값을 넣을 공간을 만들어두는 기능
 데이터 플로우 그래프를 구축할 때는 값을 넣지 않고 값을 담을 수 있는 그릇만 만들어두고, 이후에 세션
을 실행할 때 그릇에 값을 넣고 실행할 수 있습니다
'''
'''
• tensoflow.sqrt(x): x의 제곱근을 계산
• tensoflow.reduce_mean(x): x의 평균을 계산
• tensoflow.square(x): x의 제곱을 계산
• random_uniform([1], 0, 10,…) : 0에서 10 사
이에서 임의의 수 1개 생성 반환
• Variable() : 변수의 값을 지정
'''
import tensorflow as tf
#placeholder 정의(정수 자료형 3개를 가진 배열)
a = tf.placeholder(tf.int32, [3])
b = tf.constant(2)
x2_op = a* b
#세션 시작
sess = tf.Session()
# placeholder에 값 넣고 실행하기
r1 = sess.run(x2_op, feed_dict = {a:[1, 2, 3]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10, 20, 10]})
print(r2)

[2 4 6]
[20 40 20]


In [7]:
import tensorflow as tf
#placeholder 정의(정수 자료형 3개를 가진 배열)
a = tf.placeholder(tf.int32, [3])
b = tf.constant(2)
x2_op = a* b
#세션 시작
sess = tf.Session()
# placeholder에 값 넣고 실행하기
r1 = sess.run(x2_op, feed_dict = {a:[1, 2, 3]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10, 20, 10]})
print(r2)

[2 4 6]
[20 40 20]


In [8]:
import tensorflow as tf
#placeholder 정의( 배열의 크기를 None으로 지정)
a = tf.placeholder(tf.int32, [None])
b = tf.constant(10)
x10_op = a* b
#세션 시작
sess = tf.Session()
# placeholder에 값 넣고 실행하기
r1 = sess.run(x10_op, feed_dict = {a:[1, 2, 3, 4, 5]})
print(r1)
r2 = sess.run(x10_op, feed_dict = {a:[10, 20]})
print(r2)

[10 20 30 40 50]
[100 200]


In [10]:
# 예제: SVM기법으로 BMI 지수를 판정해보자 
'''
 SVM으로 BMI 판정
 키의 최대값은 200cm, 몸무게의 최대값은 100kg으로 정규화
 저체중(thin), 정상(normal), 비만(fat) 레이블을 one-hot-encoding [1, 0, 0], [0, 1, 0], [0, 0, 1]로 변환
 소프트 맥스 회귀방법 , 오차 함수는 교차 엔트로피 사용
 교차 엔트로피 - 2개의 확률 분포 사이에 정의되는 척도로서 교차 엔트로피 값이 작을 수록 정확한 값을 냄
 학습 계수 0.01, 경사 하강법(steepest descent method) 사용
'''
import pandas as pd
import numpy as np
import tensorflow as tf
# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어 들이기
csv = pd.read_csv("data/bmi.csv")
# 데이터 정규화
csv["height"] = csv["height"] / 200
csv["weight"] = csv["weight"] / 100
# 레이블을 배열로 변환하기 - thin=(1,0,0) / normal=(0,1,0) / fat=(0,0,1)
bclass = {"thin": [1,0,0], "normal": [0,1,0], "fat": [0,0,1]}
csv["label_pat"] = csv["label"].apply(lambda x : np.array(bclass[x]))
# 테스트를 위한 데이터 분류
test_csv = csv[15000:20000]
test_pat = test_csv[["weight","height"]]
test_ans = list(test_csv["label_pat"])

In [11]:
# 데이터 플로우 그래프 구축하기
# 플레이스홀더 선언하기
x = tf.placeholder(tf.float32, [None, 2]) # 키와 몸무게 데이터 넣기
y_ = tf.placeholder(tf.float32, [None, 3]) # 정답 레이블 넣기
# 변수 선언하기
W = tf.Variable(tf.zeros([2, 3])); # 가중치
b = tf.Variable(tf.zeros([3])); # 바이어스
# 소프트맥스 회귀 정의하기
y = tf.nn.softmax(tf.matmul(x, W) + b)
# 모델 훈련하기
cross_entropy = -tf.reduce_sum(y_ * tf.log(y))
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(cross_entropy)
# 정답률 구하기
predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(predict, tf.float32))
# 세션 시작하기
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화하기

In [12]:
# 학습시키기
for step in range(3500):
    i = (step * 100) % 14000
    rows = csv[1 + i : 1 + i + 100]
    x_pat = rows[["weight","height"]]
    y_ans = list(rows["label_pat"])
    fd = {x: x_pat, y_: y_ans}
    sess.run(train, feed_dict=fd)
    
    if step % 500 == 0:
        cre = sess.run(cross_entropy, feed_dict=fd)
        acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
        print("step=", step, "cre=", cre, "acc=", acc)
# 최종적인 정답률 구하기
acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
print("정답률 =", acc)

step= 0 cre= 106.53722 acc= 0.3808
step= 500 cre= 53.56096 acc= 0.8708
step= 1000 cre= 40.585423 acc= 0.8818
step= 1500 cre= 35.822723 acc= 0.9172
step= 2000 cre= 35.747204 acc= 0.9176
step= 2500 cre= 32.14396 acc= 0.9452
step= 3000 cre= 29.824009 acc= 0.9624
정답률 = 0.9656


In [1]:
'''
TensorBoard
 데이터의 흐름을 시각화하는 도구
 로그 데이터를 저장할 폴더 준비
 tensorbord –logdir = 로그데이터 저장폴더
 localhost:6006
'''
import tensorflow as tf
# 데이터 플로우 그래프 구축하기
a = tf.constant(20, name="a")
b = tf.constant(30, name="b")
mul_op = a * b
# 세션 생성하기
sess = tf.Session()
# TensorBoard 사용하기
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)#sklearn머신러닝 학습폴더 바로 하단에 폴더및 그래프 생성 
# 세션 실행하기
print(sess.run(mul_op))


600


In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어 들이기
csv = pd.read_csv("data/bmi.csv")

# 데이터 정규화
csv["height"] = csv["height"] / 200
csv["weight"] = csv["weight"] / 100

# 레이블을 배열로 변환하기
# - thin=(1,0,0) / normal=(0,1,0) / fat=(0,0,1)
bclass = {"thin": [1,0,0], "normal": [0,1,0], "fat": [0,0,1]}
csv["label_pat"] = csv["label"].apply(lambda x : np.array(bclass[x]))

# 테스트를 위한 데이터 분류
test_csv = csv[15000:20000]
test_pat = test_csv[["weight","height"]]
test_ans = list(test_csv["label_pat"])

# 플레이스홀더로 이름 붙이기
x = tf.placeholder(tf.float32, [None, 2], name="x")
y_ = tf.placeholder(tf.float32, [None, 3], name="y_")

In [4]:
# interface 부분을 스코프로 묶기
with tf.name_scope('interface') as scope:
    W = tf.Variable(tf.zeros([2, 3]), name="W"); # 가중치
    b = tf.Variable(tf.zeros([3]), name="b"); # 바이어스

# 소프트맥스 회귀 정의 --- (※7)
with tf.name_scope('softmax') as scope:
    y = tf.nn.softmax(tf.matmul(x, W) + b)

# loss 계산을 스코프로 묶기
with tf.name_scope('loss') as scope:
    cross_entropy = -tf.reduce_sum(y_ * tf.log(y))

# training 계산을 스코프로 묶기
with tf.name_scope('training') as scope:
    optimizer = tf.train.GradientDescentOptimizer(0.01)
    train = optimizer.minimize(cross_entropy)

# accuracy 계산을 스코프로 묶기
with tf.name_scope('accuracy') as scope:
    predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_,1))
    accuracy = tf.reduce_mean(tf.cast(predict, tf.float32))

In [7]:
# 세션 시작하기
with tf.Session() as sess:
    #tw = tf.train.SummaryWriter("log_dir", graph=sess.graph) #지원안함
    tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
    sess.run(tf.initialize_all_variables()) # 변수 초기화하기
   
    # 테스트 데이터를 이용해 학습하기
    for step in range(3500):
        i = (step * 100) % 14000
        rows = csv[1 + i : 1 + i + 100]
        x_pat = rows[["weight","height"]]
        y_ans = list(rows["label_pat"])
        fd = {x: x_pat, y_: y_ans}
        sess.run(train, feed_dict=fd)
        if step % 500 == 0:
            cre = sess.run(cross_entropy, feed_dict=fd)
            acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
            print("step=", step, "cre=", cre, "acc=", acc)

    # 최종적인 정답률 구하기
    acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
    print("정답률=", acc)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
step= 0 cre= 106.53722 acc= 0.3808
step= 500 cre= 53.56096 acc= 0.8708
step= 1000 cre= 40.585423 acc= 0.8818
step= 1500 cre= 35.822723 acc= 0.9172
step= 2000 cre= 35.747204 acc= 0.9176
step= 2500 cre= 32.14396 acc= 0.9452
step= 3000 cre= 29.824009 acc= 0.9624
정답률= 0.9656


In [ ]:
######################################################################################################

In [ ]:
'''
Keras
 머신러닝 라이브러리 Theano와 TensorFlow를 래핑한 라이브러리
 https://keras.io/
 Sequential로 딥러닝의 각 층을 add()로 추가
 활성화 함수, Dropout 등 add()로 간단하게 추가
 compile()로 모델 구축
 loss 로 최적화 함수 지정
 fit() 로 모델에 데이터를 학습시킴
 Keras로 머신러닝을 수행할 때 Numpy 배열 데이터를 전달해야 한다
'''


In [11]:
# Keras 이용하여 앞서 BMI 예제를 풀어보자 

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.callbacks import EarlyStopping
import pandas as pd, numpy as np

# BMI 데이터를 읽어 들이고 정규화하기
csv = pd.read_csv("data/bmi.csv")

# 몸무게와 키 데이터
csv["weight"] /= 100
csv["height"] /= 200
X = csv[["weight", "height"]].as_matrix()

# 레이블
bclass = {"thin":[1,0,0], "normal":[0,1,0], "fat":[0,0,1]}
y = np.empty((20000,3))
for i, v in enumerate(csv["label"]):
    y[i] = bclass[v]

# 훈련 전용 데이터와 테스트 전용 데이터로 나누기
X_train, y_train = X[1:15001], y[1:15001]
X_test, y_test = X[15001:20001], y[15001:20001]

# 모델 구조 정의하기
model = Sequential()
model.add(Dense(512, input_shape=(2,)))
model.add(Activation('relu'))
model.add(Dropout(0.1))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.1))
model.add(Dense(3))
model.add(Activation('softmax'))

C:\Users\student\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [12]:

# 모델 구축하기
model.compile( loss='categorical_crossentropy', optimizer="rmsprop", metrics=['accuracy'])

# 데이터 훈련하기
hist = model.fit(
    X_train, y_train,
    batch_size=100,
    nb_epoch=20,
    validation_split=0.1,
    callbacks=[EarlyStopping(monitor='val_loss', patience=2)],
    verbose=1)

# 테스트 데이터로 평가하기
score = model.evaluate(X_test, y_test)
print('loss=', score[0])
print('accuracy=', score[1])

C:\Users\student\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel_launcher.py:11: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  # This is added back by InteractiveShellApp.init_path()





Train on 13500 samples, validate on 1500 samples
Epoch 1/20
13500/13500 [==============================] - 1s 98us/step - loss: 0.5089 - accuracy: 0.7964 - val_loss: 0.2687 - val_accuracy: 0.8960
Epoch 2/20
13500/13500 [==============================] - 1s 74us/step - loss: 0.2473 - accuracy: 0.9014 - val_loss: 0.1662 - val_accuracy: 0.9460
Epoch 3/20
13500/13500 [==============================] - 1s 73us/step - loss: 0.1895 - accuracy: 0.9208 - val_loss: 0.1186 - val_accuracy: 0.9807
Epoch 4/20
13500/13500 [==============================] - 1s 73us/step - loss: 0.1613 - accuracy: 0.9359 - val_loss: 0.1011 - val_accuracy: 0.9760
Epoch 5/20
13500/13500 [==============================] - 1s 75us/step - loss: 0.1480 - accuracy: 0.9350 - val_loss: 0.1888 - val_accuracy: 0.9027
Epoch 6/20
13500/13500 [==============================] - 1s 74us/step - loss: 0.1354 - accuracy: 0.9432 - val_loss: 0.0814 - val_accuracy: 0.9813
Epoch 7/20
13500/13500 [==============================] - 1s 73us/

In [ ]:
'''
Keras이용 BMI 판정
 weight decay( 가중치 감소) - 학습중 가중치가 큰 것에 대해서 패널티를 부과해 과적합의 위험을 줄이는 방법
 Dropout - 복잡한 신경망에서 가중치 감소만으로 과적합을 피하기 어려운 경우 뉴런의 연결을 임의로 삭제시켜 신호
를 전달하지 못하도록 하는 방법
 softmax 회귀 - 입력받은 값을 출력으로 0~1사이의 값으로 모두 정규화하여 출력값들의 총합은 항상 1이 되는 특성의
함수
 분류하고 싶은 클래스 수 만큼 출력으로 구성
 소프트 맥스 결과값을 One hot encoder의 입력으로 연결하면 가장 큰 값만 True값, 나머지는 False
값이 나오게 하여 이용 가능하다
 val_loss는 에포크 힛수가 많아질 수록 감소하다가 다시 증가됨을 보이는 경우, 과적합이 발생한 것입니다.
 학습에 더 이상 개선의 여지가 없을 경우 학습을 종료시키는 콜백함수(수행중인 함수에서 지정된 함수를 호출,되부름)
는 EarlyStopping 입니다.
 Dense(출력 뉴런의 수, input_dim=입력 뉴런의 수, init= 가중치 초기화 방법, activation=활성화 함수)
 relu 활성화 함수는 은닉층에 주로 사용
 sigmoid 활성화 함수는 이진 분류 문제에서 출력층에 주로 사용
 softmax 활성화 함수는 다중 클래스 분류 문제에서 출력층에 주로 사용

'''