In [1]:
####4장 운용용 어플리케이션과 5부 스트리밍은 엔지니어링 분야야 맞물려 생략 ###
#### 6장 고급 분석과 머신러닝 개요부터 다시 설명 (p.555)###

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Test").config("spark.executor.instances", "1").config("spark.executor.cores", "1").config("spark.executor.memory", "2g").config("spark.driver.memory", "2g").getOrCreate()

In [2]:
import numpy as np 
import scipy.sparse as sps
from pyspark.mllib.linalg import Vectors 

In [4]:
# dense vector 
v1 = np.array([0.1, 0.0, 0.2, 0.3])
v2 = Vectors.dense([0.1, 0.0, 0.2, 0.3])
v3 = [0.1, 0.0, 0.2, 0.3]



In [5]:
v1

array([0.1, 0. , 0.2, 0.3])

In [6]:
v2

DenseVector([0.1, 0.0, 0.2, 0.3])

In [7]:
v3

[0.1, 0.0, 0.2, 0.3]

In [9]:
# sparse vector 
v3 = Vectors.sparse(4, [(0, 0.1), (2, 0.2), (3, 0.3)]) #4행 1열, 1에 대한 요소가 없음 
v4 = Vectors.sparse(4, [0, 2, 3], [0.1, 0.2, 0.3])
v5 = sps.csc_matrix((np.array([0.1, 0.2, 0.3]), np.array([0, 2, 3]), np.array([0, 3])), shape = (4, 1))


In [10]:
v3 

SparseVector(4, {0: 0.1, 2: 0.2, 3: 0.3})

In [11]:
v4

SparseVector(4, {0: 0.1, 2: 0.2, 3: 0.3})

In [13]:
v5

  (0, 0)	0.1
  (2, 0)	0.2
  (3, 0)	0.3


In [18]:
print(v1)
print(v2)
print(v3)
print(v4)
print(v5)

[0.1 0.  0.2 0.3]
[0.1,0.0,0.2,0.3]
(4,[0,2,3],[0.1,0.2,0.3])
(4,[0,2,3],[0.1,0.2,0.3])
  (0, 0)	0.1
  (2, 0)	0.2
  (3, 0)	0.3


In [20]:
#만약 아무값도 입력하지 않는다면? 
import numpy as np 
from scipy.sparse import csc_matrix

csc_matrix((3,4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [21]:
row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])

csc_matrix((data, (row, col)), shape=(3, 3)).toarray()


array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]], dtype=int64)

In [22]:
indptr = np.array([0, 2, 3, 6])  #CSC format index array
indices = np.array([0, 2, 2, 0, 1, 2]) #CSC format index pointer array(행 인덱스)
data = np.array([1, 2, 3, 4, 5, 6])
csc_matrix((data, indices, indptr), shape=(3, 3)).toarray()


array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]])